### ISSUE TITLE
기능 개선 의견

### ISSUE THREAD

**Issue by iaintnowhere** [genonfire/rulli#1]
![본문](https://user-images.githubusercontent.com/59553849/211771568-6eacf092-53f8-433d-85b6-7219c726f9b8.jpg)

루리웹 핫딜게 본문에도 링크가 바뀌는데 이것도 포함해주시면 좋겠네요..

**Comment by genonfire** [comment]
본문은 검출 영역 밖이라 포함시킬 경우 룰리웹 다른 페이지를 접속할 때 속도 및 기능에 영향을 끼칠 우려가 있어 적용이 힘듭니다.
